from typing import Protocol

from conode.domain.company import CompanyId
from conode.domain.role import Role, RoleId, RoleName
from conode.domain.user import UserId


class RoleRepository(Protocol):
    async def update(self, role: Role) -> None: ...
    async def delete(self, role: Role) -> None: ...
    async def create(self, role: Role) -> None: ...
    async def get_by_id(self, role_id: RoleId) -> Role: ...
    async def get_all_by_ids(self, roles_ids: list[RoleId]) -> list[Role]: ...
    async def get_all_by_user_id(self, user_id: UserId) -> list[Role]: ...
    async def get_by_name_and_company_id(
        self, name: RoleName, company_id: CompanyId
    ) -> Role | None: ...
