
service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [nop]
      processors: [batch]
      exporters: [nop]
  telemetry:
    resource:
      service.name: jaeger-query
    logs:
      level: info

extensions:
  healthcheckv2:
    use_v2: true
    http:

  jaeger_query:
    storage:
      traces: query_storage
    ui:
      config_file: /jaeger/config-ui.json

  jaeger_storage:
    backends:
      query_storage:
        clickhouse:
          addresses:
            - clickhouse:9000
          database: jaeger
          auth:
            basic:
              username: jaeger
              password: jaegerSecretPassword

receivers:
  nop:

processors:
  batch:

exporters:
  nop: