"""parent_group_id

Revision ID: 0333150881b1
Revises: 4a52d766f55e
Create Date: 2026-06-25 19:10:38.311452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0333150881b1'
down_revision: Union[str, Sequence[str], None] = '4a52d766f55e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_record', sa.Column('parent_group_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'group_record', 'group_record', ['parent_group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group_record', type_='foreignkey')
    op.drop_column('group_record', 'parent_group_id')
    # ### end Alembic commands ###
