"""remove-company-id

Revision ID: 1786a4b3cea6
Revises: 6c7e8a84a7c8
Create Date: 2026-05-12 15:27:23.248594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1786a4b3cea6'
down_revision: Union[str, Sequence[str], None] = '6c7e8a84a7c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('node_association_record_company_id_fkey'), 'node_association_record', type_='foreignkey')
    op.drop_column('node_association_record', 'company_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node_association_record', sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('node_association_record_company_id_fkey'), 'node_association_record', 'company_record', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
