"""unique-constrait

Revision ID: 4a8ee55b96fa
Revises: 0333150881b1
Create Date: 2026-06-28 09:54:53.692020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a8ee55b96fa'
down_revision: Union[str, Sequence[str], None] = '0333150881b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_node_association_record_group_id_node_id', 'node_association_record', ['group_id', 'node_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_node_association_record_group_id_node_id', 'node_association_record', type_='unique')
    # ### end Alembic commands ###
