"""permission-type-offer

Revision ID: 504f086cc1a2
Revises: 2e3b8d977df1
Create Date: 2026-05-14 13:21:31.797120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '504f086cc1a2'
down_revision: Union[str, Sequence[str], None] = '2e3b8d977df1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer_context_record', sa.Column('permission_type', sa.Enum('READ', 'MODIFY', name='permissiontype'), nullable=False))
    op.add_column('offer_group_record', sa.Column('permission_type', sa.Enum('READ', 'MODIFY', name='permissiontype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer_group_record', 'permission_type')
    op.drop_column('offer_context_record', 'permission_type')
    # ### end Alembic commands ###
