"""remove-owner-id

Revision ID: 6240bee5cfae
Revises: 080a7bac6dfb
Create Date: 2026-05-12 16:01:37.091566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6240bee5cfae'
down_revision: Union[str, Sequence[str], None] = '080a7bac6dfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('permission_record_owner_company_id_fkey'), 'permission_record', type_='foreignkey')
    op.drop_column('permission_record', 'owner_company_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission_record', sa.Column('owner_company_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('permission_record_owner_company_id_fkey'), 'permission_record', 'company_record', ['owner_company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
