"""edge-company-id

Revision ID: 658eaeeb4857
Revises: 78521bfa1ec2
Create Date: 2026-05-09 15:21:54.498267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '658eaeeb4857'
down_revision: Union[str, Sequence[str], None] = '78521bfa1ec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node_association_record', sa.Column('company_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'node_association_record', 'company_record', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'node_association_record', type_='foreignkey')
    op.drop_column('node_association_record', 'company_id')
    # ### end Alembic commands ###
