"""contexts-and-edges

Revision ID: 78521bfa1ec2
Revises: ee89ddc73033
Create Date: 2026-05-09 14:45:05.719741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78521bfa1ec2'
down_revision: Union[str, Sequence[str], None] = 'ee89ddc73033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edge_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_a_id', sa.UUID(), nullable=False),
    sa.Column('node_b_id', sa.UUID(), nullable=False),
    sa.Column('context_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company_record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['context_id'], ['context_record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_a_id'], ['node_record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_b_id'], ['node_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edge_record')
    # ### end Alembic commands ###
