"""unique-company-name

Revision ID: a3029168e306
Revises: 74a91a825965
Create Date: 2026-08-09 12:07:58.394174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3029168e306'
down_revision: Union[str, Sequence[str], None] = '74a91a825965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'company_record', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company_record', type_='unique')
    # ### end Alembic commands ###
