"""nodes-and-groups

Revision ID: b5ff44a6d487
Revises: 33f30ca8ca69
Create Date: 2026-05-08 09:56:21.411247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5ff44a6d487'
down_revision: Union[str, Sequence[str], None] = '33f30ca8ca69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR, nullable=False),
    sa.Column('description', sa.VARCHAR, nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('node_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR, nullable=False),
    sa.Column('description', sa.VARCHAR, nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('node_association_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group_record.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['node_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('node_association_record')
    op.drop_table('node_record')
    op.drop_table('group_record')
    # ### end Alembic commands ###
