"""refresh-token-and-unique-constrait

Revision ID: bf7551bea9b4
Revises: be8366314bd6
Create Date: 2026-08-17 12:43:15.774966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf7551bea9b4'
down_revision: Union[str, Sequence[str], None] = 'be8366314bd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_record', sa.Column('ip', sa.String(), nullable=False))
    op.add_column('session_record', sa.Column('refresh_token', sa.String(), nullable=False))
    op.create_unique_constraint('uq_session_record_user_id_ip', 'session_record', ['user_id', 'ip'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_session_record_user_id_ip', 'session_record', type_='unique')
    op.drop_column('session_record', 'refresh_token')
    op.drop_column('session_record', 'ip')
    # ### end Alembic commands ###
