"""email-flag

Revision ID: d196baf978b0
Revises: 4574d0b1f6b0
Create Date: 2026-08-11 15:58:28.896881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd196baf978b0'
down_revision: Union[str, Sequence[str], None] = '4574d0b1f6b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_record', sa.Column('email_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_record', 'email_verified')
    # ### end Alembic commands ###
