"""association-cascade

Revision ID: ee772395dc0d
Revises: b5ff44a6d487
Create Date: 2026-05-09 09:05:33.966857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee772395dc0d'
down_revision: Union[str, Sequence[str], None] = 'b5ff44a6d487'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('node_association_record_group_id_fkey'), 'node_association_record', type_='foreignkey')
    op.drop_constraint(op.f('node_association_record_node_id_fkey'), 'node_association_record', type_='foreignkey')
    op.create_foreign_key(None, 'node_association_record', 'node_record', ['node_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'node_association_record', 'group_record', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'node_association_record', type_='foreignkey')
    op.drop_constraint(None, 'node_association_record', type_='foreignkey')
    op.create_foreign_key(op.f('node_association_record_node_id_fkey'), 'node_association_record', 'node_record', ['node_id'], ['id'])
    op.create_foreign_key(op.f('node_association_record_group_id_fkey'), 'node_association_record', 'group_record', ['group_id'], ['id'])
    # ### end Alembic commands ###
