services:
  api:
    build: .
    restart: on-failure
    container_name: api
    command: ["conode", "api", "run"]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - conode-network
    labels:
      - "traefik.enable=true"
      - traefik.http.services.api-conode.loadbalancer.server.port=8000
      - "traefik.http.routers.whoami.rule=Host(`api.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls=true"

  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      conode-network:
        aliases:
          - persistence.literally.io
    env_file:
      - "./deploy/postgres.env"

  traefik:
    image: traefik:v3.6
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

    networks:
      - conode-network

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/certs:ro
      - ./deploy/traefik/dynamic:/dynamic:ro

    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"

      - "--providers.file.filename=/dynamic/tls.yaml"

      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=conode-network"

      - "--api.dashboard=true"
      - "--api.insecure=false"

      - "--log.level=INFO"
      - "--accesslog=true"
      - "--metrics.prometheus=true"

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.dashboard.rule=Host(`dashboard.localhost`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"

      - "traefik.http.middlewares.dashboard-auth.basicauth.users=admin:$$apr1$$EyDesxOz$$PpFwyKkBg45I271SSZRPA1"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth@docker"

volumes:
  postgres-data:

networks:
  conode-network:
    driver: bridge