services:
  api:
    build: .
    restart: on-failure
    container_name: api
    command: ["conode", "api", "run"]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - conode-network

  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      conode-network:
        aliases:
          - persistence.literally.io
    env_file:
      - "./deploy/postgres.env"

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    networks:
      conode-network:
        aliases:
          - literally.io
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

volumes:
  prometheus-data:
  grafana-data:
  postgres-data:
  rustfs-data:

networks:
  conode-network:
    driver: bridge