services:
  api:
    environment:
      DEBUG: "true"
    volumes:
      - "./src/prodik/:/prodik/src/prodik/"

  redis:
    ports:
     - 6379:6379

  postgres:
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5