[api]
host = "0.0.0.0"
port = 8000

[database]
database = "conode"
username = "conode"
password = "conodeSecretPassword"
host = "persistence.literally.io"
port = 5432

[secrets]
expires_in = 3600
private_key_file_path = "/conode/src/conode/infrastructure/credentials/private.pem"
public_key_file_path = "/conode/src/conode/infrastructure/credentials/public.pem"
issuer = "https://api.conode.com/"
audience = "conode"

[telemetry]
endpoint = "alloy:4317"
enabled = false