[api]
host = "0.0.0.0"
port = 8000

[database]
username = "postgres"
password = "admin_password"
host = "persistence.literally.io"
database = "postgres"
port = 5432

[secrets]
secret = "ABC123"
expires_in = 3600
jwks_url = "http://keycloak:8080/realms/conode/protocol/openid-connect/certs"
issuer = "http://keycloak.conode.com/realms/conode"
audience = "conode"

[telemetry]
endpoint = "collector:4317"
enabled = true