[api]
host = "0.0.0.0"
port = 8000

[database]
database = "conode"
username = "conode"
password = "conodeSecretPassword"
host = "persistence.literally.io"
port = 5432

[secrets]
secret = "ABC123"
expires_in = 3600
jwks_url = "http://keycloak:8080/realms/conode/protocol/openid-connect/certs"
issuer = "http://keycloak.conode.com/realms/conode"
audience = "conode"

[telemetry]
endpoint = "alloy:4317"
enabled = false