from prodik.application.errors import ApplicationError


class GroupDomainValidationError(ApplicationError): ...


class InvalidGroupNameFormatError(GroupDomainValidationError): ...


class InvalidGroupDescriptionFormatError(GroupDomainValidationError): ...


class GroupCannotInheritedFromItselfError(GroupDomainValidationError): ...
