from conode.application.errors import ApplicationError


class OfferDomainValidationError(ApplicationError): ...


class InvalidOfferTitleFormatError(OfferDomainValidationError): ...


class InvalidOfferDescriptionFormatError(OfferDomainValidationError): ...


class OfferCannotAnswerToItself(OfferDomainValidationError): ...