from typing import Protocol

from prodik.domain.authorization import Session
from prodik.domain.user import UserId


class SessionRepository(Protocol):
    async def create(self, session: Session) -> None: ...
    async def update(self, prev_token: str, session: Session) -> None: ...
    async def get_by_host_and_user_id(
        self, user_id: UserId, host: str
    ) -> Session | None: ...
    async def get_by_token(self, token: str) -> Session: ...
