upstreams=["http://api:8000"]
http_address="0.0.0.0:4180"
reverse_proxy=true
cookie_httponly=true
request_logging=true
auth_logging=true
standard_logging=true
skip_provider_button=true
set_xauthrequest=true
pass_authorization_header=true
set_authorization_header=true
pass_access_token=true
insecure_oidc_allow_unverified_email=true
provider="oidc"
redirect_url="http://api.conode.com/oauth2/callback"
oidc_issuer_url="http://keycloak.conode.com/realms/conode"
scope="openid email profile offline_access"
code_challenge_method="S256"
email_domains="*"
cookie_domains=[".conode.com"]
whitelist_domains=[".conode.com"]
cookie_refresh="0h4m0s"
cookie_expire="720h0m0s"
cookie_secure=false
cookie_csrf_per_request = true