from prodik.application.errors import ApplicationError


class UserDomainValidationError(ApplicationError): ...


class InvalidUserUsernameFormatError(UserDomainValidationError): ...


class InvalidUserFirstNameFormatError(UserDomainValidationError): ...


class InvalidUserLastNameFormatError(UserDomainValidationError): ...


class InvalidUserEmailFormatError(UserDomainValidationError): ...
