from typing import Protocol

from prodik.domain.company import Company, CompanyId, CompanyName
from prodik.domain.user import UserId


class CompanyRepository(Protocol):
    async def get_by_user_id(self, user_id: UserId) -> Company | None: ...
    async def get_by_name(self, name: CompanyName) -> Company | None: ...
    async def get_by_id(self, company_id: CompanyId) -> Company | None: ...
    async def create(self, company: Company) -> None: ...
    async def update(self, company: Company) -> None: ...
