from typing import Protocol

from prodik.domain.company import CompanyId
from prodik.domain.context import Context, ContextId


class ContextRepository(Protocol):
    async def create(self, context: Context) -> None: ...
    async def delete(self, context: Context) -> None: ...
    async def get_by_id(self, context_id: ContextId) -> Context | None: ...
    async def get_all_by_company_id(self, company_id: CompanyId) -> list[Context]: ...
