from typing import Protocol

from prodik.domain.edge import Edge, EdgeId


class EdgeRepository(Protocol):
    async def create(self, edge: Edge) -> None: ...
    async def delete(self, edge: Edge) -> None: ...
    async def update(self, edge: Edge) -> None: ...
    async def get_by_id(self, id: EdgeId) -> Edge | None: ...
