from typing import Protocol

from prodik.domain.context import ContextId
from prodik.domain.edge import Edge, EdgeId
from prodik.domain.node import NodeId


class EdgeRepository(Protocol):
    async def create(self, edge: Edge) -> None: ...
    async def delete(self, edge: Edge) -> None: ...
    async def update(self, edge: Edge) -> None: ...
    async def get_by_id(self, edge_id: EdgeId) -> Edge | None: ...
    async def get_all_by_context_id(self, context_id: ContextId) -> list[Edge]: ...
    async def get_all_connecting_edges_by_nodes(self, node_a: NodeId, node_b: NodeId) -> list[Edge]: ...
    async def get_all_by_node_and_context(self, node_id: NodeId, context_id: ContextId) -> list[Edge]: ...
    async def get_by_nodes_and_context(
        self,
        node_a_id: NodeId,
        node_b_id: NodeId,
        context_id: ContextId,
    ) -> Edge | None: ...
