from typing import Protocol

from prodik.domain.company import CompanyId
from prodik.domain.group import Group, GroupId


class GroupRepository(Protocol):
    async def create(self, group: Group) -> None: ...
    async def delete(self, group: Group) -> None: ...
    async def get_by_id(self, group_id: GroupId) -> Group | None: ...
    async def get_all_by_company_id(self, company_id: CompanyId) -> list[Group]: ...
    async def get_all_by_ids(self, group_ids: list[GroupId]) -> list[Group]: ...
