from typing import Protocol

from prodik.domain.node import Node, NodeAssociation, NodeAssociationId, NodeId


class NodeRepository(Protocol):
    async def create(self, node: Node) -> None: ...
    async def update(self, node: Node) -> None: ...
    async def delete(self, node: Node) -> None: ...
    async def get_by_id(self, id: NodeId) -> Node | None: ...
    async def get_all_by_ids(self, nodes: list[NodeId]) -> list[Node]: ...


class NodeAssociationRepository(Protocol):
    async def create(self, node_association: NodeAssociation) -> None: ...
    async def delete(self, node_association: NodeAssociation) -> None: ...
    async def get_by_id(self, id: NodeAssociationId) -> NodeAssociation | None: ...
    async def create_all(self, node_association: list[NodeAssociation]) -> None: ...
