from typing import Protocol

from prodik.domain.group import GroupId
from prodik.domain.node import Node, NodeAssociation, NodeAssociationId, NodeId


class NodeRepository(Protocol):
    async def create(self, node: Node) -> None: ...
    async def update(self, node: Node) -> None: ...
    async def delete(self, node: Node) -> None: ...
    async def get_by_id(self, node_id: NodeId) -> Node: ...
    async def get_all_by_ids(self, nodes_ids: list[NodeId]) -> list[Node]: ...
    async def get_all_by_associations(
        self,
        associations: list[NodeAssociation],
    ) -> list[Node]: ...


class NodeAssociationRepository(Protocol):
    async def create(self, node_association: NodeAssociation) -> None: ...
    async def delete(self, node_association: NodeAssociation) -> None: ...
    async def get_by_id(
        self,
        node_association_id: NodeAssociationId,
    ) -> NodeAssociation: ...
    async def create_all(self, node_association: list[NodeAssociation]) -> None: ...
    async def get_by_node_id(self, node_id: NodeId) -> NodeAssociation | None: ...
    async def get_all_by_node_id(self, node_id: NodeId) -> list[NodeAssociation]: ...
    async def get_all_by_group_id(self, group_id: GroupId) -> list[NodeAssociation]: ...
