from typing import Protocol

from prodik.domain.offer import Offer, OfferContext, OfferGroup, OfferId, OfferLink


class OfferRepository(Protocol):
    async def create(self, offer: Offer) -> None: ...
    async def update(self, offer: Offer) -> None: ...
    async def get_by_id(self, offer_id: OfferId) -> Offer | None: ...


class OfferGroupRepository(Protocol):
    async def create_all(self, offer_groups: list[OfferGroup]) -> None: ...
    async def get_by_offer_id(self, offer_id: OfferId) -> list[OfferGroup]: ...


class OfferContextRepository(Protocol):
    async def create_all(self, offer_contexts: list[OfferContext]) -> None: ...
    async def get_by_offer_id(self, offer_id: OfferId) -> list[OfferContext]: ...


class OfferLinkRepository(Protocol):
    async def create(self, offer_link: OfferLink) -> None: ...
    async def update(self, offer_link: OfferLink) -> None: ...
    async def get_by_offers_ids(
        self, from_offer_id: OfferId, to_offer_id: OfferId
    ) -> OfferLink | None: ...
