from typing import Protocol

from prodik.domain.company import CompanyId
from prodik.domain.role import Role, RoleId, RoleName


class RoleRepository(Protocol):
    async def update(self, role: Role) -> None: ...
    async def delete(self, role: Role) -> None: ...
    async def create(self, role: Role) -> None: ...
    async def get_by_name(self, name: RoleName) -> Role | None: ...
    async def get_by_id(self, role_id: RoleId) -> Role: ...
    async def get_all_by_ids(self, roles_ids: list[RoleId]) -> list[Role]: ...
    async def get_by_name_and_company_id(
        self, name: RoleName, company_id: CompanyId
    ) -> Role | None: ...
