from typing import Protocol

from prodik.domain.role import Role, RoleId, RoleName


class RoleRepository(Protocol):
    async def update(self, role: Role) -> None: ...
    async def delete(self, role: Role) -> None: ...
    async def create(self, role: Role) -> None: ...
    async def get_by_name(self, name: RoleName) -> Role | None: ...
    async def get_by_id(self, role_id: RoleId) -> Role | None: ...
    async def get_all_by_ids(self, role_ids: list[RoleId]) -> list[Role]: ...
