from prodik.application.errors import ApplicationError


class OfferDomainValidationError(ApplicationError): ...


class InvalidOfferTitleFormatError(OfferDomainValidationError): ...


class InvalidOfferDescriptionFormatError(OfferDomainValidationError): ...


class OfferCannotAnswerToItselfError(OfferDomainValidationError): ...


class OfferCannotCreateChainsError(OfferDomainValidationError): ...


class OfferIsNotCounterOfferError(OfferDomainValidationError): ...


class OfferCannotExpireAtPastError(OfferDomainValidationError): ...
