"""offers-and-contracts

Revision ID: 2e3b8d977df1
Revises: 6240bee5cfae
Create Date: 2026-05-14 12:24:06.686605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e3b8d977df1'
down_revision: Union[str, Sequence[str], None] = '6240bee5cfae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.VARCHAR, nullable=False),
    sa.Column('description', sa.VARCHAR, nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DECLINED', 'ACCEPTED', name='offerstatus'), nullable=False),
    sa.Column('from_company_id', sa.UUID(), nullable=False),
    sa.Column('to_company_id', sa.UUID(), nullable=False),
    sa.Column('from_offer', sa.UUID(), nullable=True),
    sa.Column('requires_counteroffer', sa.Boolean(), nullable=False),
    sa.Column('expires_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_company_id'], ['company_record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_offer'], ['offer_record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_company_id'], ['company_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELLED', 'EXPIRED', name='contractstatus'), nullable=False),
    sa.Column('company_a_id', sa.UUID(), nullable=False),
    sa.Column('company_b_id', sa.UUID(), nullable=False),
    sa.Column('company_a_offer_id', sa.UUID(), nullable=False),
    sa.Column('company_b_offer_id', sa.UUID(), nullable=False),
    sa.Column('company_a_role_id', sa.UUID(), nullable=False),
    sa.Column('company_b_role_id', sa.UUID(), nullable=False),
    sa.Column('expires_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_a_id'], ['company_record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_a_offer_id'], ['offer_record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_a_role_id'], ['role_record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_b_id'], ['company_record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_b_offer_id'], ['offer_record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_b_role_id'], ['role_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offer_context_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('context_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['context_record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_id'], ['offer_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offer_group_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group_record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_id'], ['offer_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offer_link_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_offer_id', sa.UUID(), nullable=False),
    sa.Column('response_offer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACCEPTED', 'ABORTED', 'PENDING', name='offerlinkstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_offer_id'], ['offer_record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_offer_id'], ['offer_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offer_link_record')
    op.drop_table('offer_group_record')
    op.drop_table('offer_context_record')
    op.drop_table('contract_record')
    op.drop_table('offer_record')
    # ### end Alembic commands ###
