"""nullable-from

Revision ID: 4a52d766f55e
Revises: 504f086cc1a2
Create Date: 2026-05-14 13:29:35.078867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a52d766f55e'
down_revision: Union[str, Sequence[str], None] = '504f086cc1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contract_record', 'company_b_offer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('contract_record', 'company_b_role_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('offer_record', 'from_company_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offer_record', 'from_company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('contract_record', 'company_b_role_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('contract_record', 'company_b_offer_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
