"""edge-unique-constrait

Revision ID: 5192c880eb4e
Revises: 4a8ee55b96fa
Create Date: 2026-07-02 09:25:00.984222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5192c880eb4e'
down_revision: Union[str, Sequence[str], None] = '4a8ee55b96fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_edge_record_node_a_id_node_b_id_context_id', 'edge_record', ['context_id', 'node_a_id', 'node_b_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_edge_record_node_a_id_node_b_id_context_id', 'edge_record', type_='unique')
    # ### end Alembic commands ###
