"""renamed-hashed-password-name

Revision ID: 6c046693f2e1
Revises: 88413fda6e9e
Create Date: 2026-05-07 12:48:30.323020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c046693f2e1'
down_revision: Union[str, Sequence[str], None] = '88413fda6e9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('local_authorization_record', sa.Column('password', sa.String(), nullable=False))
    op.drop_column('local_authorization_record', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('local_authorization_record', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('local_authorization_record', 'password')
    # ### end Alembic commands ###
