"""initial

Revision ID: 88413fda6e9e
Revises: 
Create Date: 2026-05-07 11:48:03.431262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88413fda6e9e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('system_role', sa.Enum('USER', 'ADMIN', name='usersystemrole'), nullable=False),
    sa.Column('username', sa.VARCHAR, nullable=False),
    sa.Column('last_name', sa.VARCHAR, nullable=False),
    sa.Column('first_name', sa.VARCHAR, nullable=False),
    sa.Column('email', sa.VARCHAR, nullable=False),
    sa.Column('bio', sa.String(), nullable=False),
    sa.Column('token_revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('local_authorization_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_record')
    op.drop_table('local_authorization_record')
    op.drop_table('user_record')
    # ### end Alembic commands ###
