"""roles-and-permissions

Revision ID: e60ec6d4a0a5
Revises: 658eaeeb4857
Create Date: 2026-05-11 12:23:30.442800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e60ec6d4a0a5'
down_revision: Union[str, Sequence[str], None] = '658eaeeb4857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_company_id'], ['company_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('owner_company_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('permission', sa.Enum('READ', 'MODIFY', name='permissiontype'), nullable=False),
    sa.Column('entity_type', sa.Enum('NODE', 'GROUP', 'CONTEXT', 'COMPANY', name='entitytype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_company_id'], ['company_record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permission_record')
    op.drop_table('role_record')
    # ### end Alembic commands ###
