"""contexts

Revision ID: ee89ddc73033
Revises: ee772395dc0d
Create Date: 2026-05-09 13:34:19.274591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee89ddc73033'
down_revision: Union[str, Sequence[str], None] = 'ee772395dc0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR, nullable=False),
    sa.Column('description', sa.VARCHAR, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('company_record_owner_id_fkey'), 'company_record', type_='foreignkey')
    op.create_foreign_key(None, 'company_record', 'user_record', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('group_record_company_id_fkey'), 'group_record', type_='foreignkey')
    op.create_foreign_key(None, 'group_record', 'company_record', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('local_authorization_record_user_id_fkey'), 'local_authorization_record', type_='foreignkey')
    op.create_foreign_key(None, 'local_authorization_record', 'user_record', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('node_record_company_id_fkey'), 'node_record', type_='foreignkey')
    op.create_foreign_key(None, 'node_record', 'company_record', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('session_record_user_id_fkey'), 'session_record', type_='foreignkey')
    op.create_foreign_key(None, 'session_record', 'user_record', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session_record', type_='foreignkey')
    op.create_foreign_key(op.f('session_record_user_id_fkey'), 'session_record', 'user_record', ['user_id'], ['id'])
    op.drop_constraint(None, 'node_record', type_='foreignkey')
    op.create_foreign_key(op.f('node_record_company_id_fkey'), 'node_record', 'company_record', ['company_id'], ['id'])
    op.drop_constraint(None, 'local_authorization_record', type_='foreignkey')
    op.create_foreign_key(op.f('local_authorization_record_user_id_fkey'), 'local_authorization_record', 'user_record', ['user_id'], ['id'])
    op.drop_constraint(None, 'group_record', type_='foreignkey')
    op.create_foreign_key(op.f('group_record_company_id_fkey'), 'group_record', 'company_record', ['company_id'], ['id'])
    op.drop_constraint(None, 'company_record', type_='foreignkey')
    op.create_foreign_key(op.f('company_record_owner_id_fkey'), 'company_record', 'user_record', ['owner_id'], ['id'])
    op.drop_table('context_record')
    # ### end Alembic commands ###
