from typing import Protocol

from conode.domain.auth import Session
from conode.domain.user import User


class SessionRepository(Protocol):
    async def create(self, session: Session) -> None: ...
    async def update(self, session: Session) -> None: ...
    async def upsert(self, session: Session) -> None: ...
    async def get_by_ip_and_user(self, user: User, ip: str) -> Session | None: ...
    async def get_by_refresh_token(self, token: str) -> Session: ...
